spring:
  datasource:
    url: jdbc:h2:mem:chinesedb
  jpa:
    show-sql: true
    properties:
      javax:
        persistence:
          schema-generation:
            #            database:
            #              action: create
            scripts:
              create-target: target/schema.sql
              action: create
  h2:
    console:
      #      http://localhost:8080/h2-console
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false