spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:${DB_FILE:~/chinesedb};DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: update

